#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import platform
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

class Ui_DELETE_2(object):
    def setupUi(self, DELETE_2):
        DELETE_2.setObjectName("DELETE_2")
        DELETE_2.resize(800, 600)
        DELETE_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(69, 92, 182, 255), stop:1 rgba(230, 202, 232, 255));")
        self.centralwidget = QtWidgets.QWidget(DELETE_2)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BACK = QtWidgets.QPushButton(self.centralwidget)
        self.BACK.setMinimumSize(QtCore.QSize(0, 44))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.BACK.setFont(font)
        self.BACK.setStyleSheet("background-color: rgb(114, 31, 203);\n"
"color: rgb(238, 238, 236);")
        self.BACK.setObjectName("BACK")
        self.horizontalLayout_2.addWidget(self.BACK)
        self.DELETE = QtWidgets.QPushButton(self.centralwidget)
        self.DELETE.setMinimumSize(QtCore.QSize(0, 44))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.DELETE.setFont(font)
        self.DELETE.setStyleSheet("background-color: rgb(114, 31, 203);\n"
"color: rgb(238, 238, 236);")
        self.DELETE.setObjectName("DELETE")
        self.horizontalLayout_2.addWidget(self.DELETE)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.class_2 = QtWidgets.QLabel(self.frame)
        self.class_2.setStyleSheet("background-color: rgb(229, 164, 244);")
        self.class_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.class_2.setTextFormat(QtCore.Qt.RichText)
        self.class_2.setAlignment(QtCore.Qt.AlignCenter)
        self.class_2.setWordWrap(False)
        self.class_2.setObjectName("class_2")
        self.verticalLayout_9.addWidget(self.class_2)
        self.inp_class = QtWidgets.QLineEdit(self.frame)
        self.inp_class.setStyleSheet("color: rgb(136, 138, 133);")
        self.inp_class.setText("")
        self.inp_class.setObjectName("inp_class")
        self.verticalLayout_9.addWidget(self.inp_class)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.name = QtWidgets.QLabel(self.frame)
        self.name.setStyleSheet("background-color: rgb(229, 164, 244);")
        self.name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.name.setTextFormat(QtCore.Qt.RichText)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setWordWrap(False)
        self.name.setObjectName("name")
        self.verticalLayout_8.addWidget(self.name)
        self.inp_name = QtWidgets.QLineEdit(self.frame)
        self.inp_name.setStyleSheet("color: rgb(136, 138, 133);")
        self.inp_name.setInputMask("")
        self.inp_name.setText("")
        self.inp_name.setObjectName("inp_name")
        self.verticalLayout_8.addWidget(self.inp_name)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Rollno = QtWidgets.QLabel(self.frame)
        self.Rollno.setStyleSheet("background-color: rgb(229, 164, 244);")
        self.Rollno.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Rollno.setTextFormat(QtCore.Qt.RichText)
        self.Rollno.setAlignment(QtCore.Qt.AlignCenter)
        self.Rollno.setWordWrap(False)
        self.Rollno.setObjectName("Rollno")
        self.verticalLayout_10.addWidget(self.Rollno)
        self.inp_rollno = QtWidgets.QLineEdit(self.frame)
        self.inp_rollno.setStyleSheet("color: rgb(136, 138, 133);")
        self.inp_rollno.setText("")
        self.inp_rollno.setObjectName("inp_rollno")
        self.verticalLayout_10.addWidget(self.inp_rollno)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        DELETE_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(DELETE_2)
        QtCore.QMetaObject.connectSlotsByName(DELETE_2)

    def retranslateUi(self, DELETE_2):
        _translate = QtCore.QCoreApplication.translate
        DELETE_2.setWindowTitle(_translate("DELETE_2", "MainWindow"))
        self.BACK.setText(_translate("DELETE_2", "BACK"))
        self.DELETE.setText(_translate("DELETE_2", "DELETE"))
        self.class_2.setText(_translate("DELETE_2", "Class"))
        self.inp_class.setPlaceholderText(_translate("DELETE_2", "enter......"))
        self.name.setText(_translate("DELETE_2", "Name"))
        self.inp_name.setPlaceholderText(_translate("DELETE_2", "enter......"))
        self.Rollno.setText(_translate("DELETE_2", "Roll No."))
        self.inp_rollno.setPlaceholderText(_translate("DELETE_2", "enter......"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DELETE_2 = QtWidgets.QMainWindow()
    ui = Ui_DELETE_2()
    ui.setupUi(DELETE_2)
    DELETE_2.show()
    sys.exit(app.exec_())
