#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import platform
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_menu(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(23)
        menu.setFont(font)
        menu.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(69, 92, 182, 255), stop:1 rgba(230, 202, 232, 255));")
        self.centralwidget = QtWidgets.QWidget(menu)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 75 27pt \"URW Bookman L\";\n"
"background-color: rgb(238, 238, 236);\n"
"color: rgb(185, 22, 226);\n"
"border-radius:20px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ADD = QtWidgets.QPushButton(self.centralwidget)
        self.ADD.setMinimumSize(QtCore.QSize(0, 44))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ADD.setFont(font)
        self.ADD.setStyleSheet("background-color: rgb(114, 31, 203);\n"
"color: rgb(238, 238, 236);")
        self.ADD.setObjectName("ADD")
        self.verticalLayout_2.addWidget(self.ADD)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.UPDATE = QtWidgets.QPushButton(self.centralwidget)
        self.UPDATE.setMinimumSize(QtCore.QSize(0, 44))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.UPDATE.setFont(font)
        self.UPDATE.setStyleSheet("background-color: rgb(114, 31, 203);\n"
"color: rgb(238, 238, 236);")
        self.UPDATE.setObjectName("UPDATE")
        self.verticalLayout_2.addWidget(self.UPDATE)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.DELETE = QtWidgets.QPushButton(self.centralwidget)
        self.DELETE.setMinimumSize(QtCore.QSize(0, 44))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.DELETE.setFont(font)
        self.DELETE.setStyleSheet("background-color: rgb(114, 31, 203);\n"
"color: rgb(238, 238, 236);")
        self.DELETE.setObjectName("DELETE")
        self.verticalLayout_2.addWidget(self.DELETE)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.FACE = QtWidgets.QPushButton(self.centralwidget)
        self.FACE.setMinimumSize(QtCore.QSize(0, 44))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.FACE.setFont(font)
        self.FACE.setStyleSheet("background-color: rgb(114, 31, 203);\n"
"color: rgb(238, 238, 236);")
        self.FACE.setObjectName("FACE")
        self.verticalLayout_2.addWidget(self.FACE)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "MainWindow"))
        self.label.setText(_translate("menu", "StAT"))
        self.ADD.setText(_translate("menu", "ADD Student"))
        self.DELETE.setText(_translate("menu", "DELETE Student"))
        self.UPDATE.setText(_translate("menu", "Capture Student Activity"))
        self.FACE.setText(_translate("menu", "Track Attendance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu = QtWidgets.QMainWindow()
    ui = Ui_menu()
    ui.setupUi(menu)
    menu.show()
    sys.exit(app.exec_())
